### ISSUE TITLE
Be more precise about first paint vs first contentful paint

### ISSUE THREAD

**Issue by npm1** [w3c/paint-timing#38]
Currently the processing model does not specify how we are supposed to track which rendering updates represent a first paint vs a first contentful paint. Instead, in "mark paint timing", the two cases are considered. It would be nice to be more rigorous here.

**Comment by noamr** [comment]
Is this fixed now? @npm1

**Comment by npm1** [comment]
It's not fixed.

**Comment by npm1** [comment]
To clarify why this is still not fixed, `mark paint timing` still says "If this instance of update the rendering is the first paint of document" and then similarly for FCP. While FCP is relatively well-defined, there is no clear way to keep track of these states. I'm not sure it's feasible to fix this, so it could be closed as "WontFix", but it's definitely not fixed.

**Comment by rniwa** [comment]
I think we need to add some flag on each document indicating whether we've done FP / FCP and then set those flags to true when the current invocation of marking paint time meets the criteria we laid out. Then the following invocations of the marking the paint time can simply exit early when those flags are set.

**Comment by yoavweiss** [comment]
> We can add boolean flags on each document indicating whether we've done FP / FCP and then set those flags to true when the current invocation of marking paint time meets the criteria we laid out. Then the following invocations of the marking the paint time can simply exit early when those flags are set.

That makes sense to me. Seems like this will require an HTML change as well (to add and initialize those flags)
